package LibrarySystem;

import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aaronm
 */
public class RentBook extends javax.swing.JFrame {

    Connection connection;
    ResultSet result;
    PreparedStatement pStatement;

    Book book;

    String ISBN;

    /**
     * Creates new form RentBook
     */
    public RentBook() {
        super("Rent Book");
        initComponents();
        connection = dbConnect.connectDb();
    }

    public RentBook(Book book) {
        initComponents();
        connection = dbConnect.connectDb();
        this.book = book;
        jTextFieldISBN.setText(book.getISBN2());
    }

    public RentBook(String ISBN) {
        initComponents();
        connection = dbConnect.connectDb();
        this.ISBN = ISBN;
        jTextFieldISBN.setText(ISBN);
    }

    public RentBook(String AccountNum, String ISBN) {
        initComponents();
        connection = dbConnect.connectDb();
        jTextFieldISBN.setText(ISBN);
        jTextFieldAccID.setText(AccountNum);
    }

    public int generateRentID() {

        int id;

        Random r = new Random();
        id = r.nextInt(10000000 + 1);

        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelPages = new javax.swing.JLabel();
        jLabelBookName = new javax.swing.JLabel();
        jLabelPublisher = new javax.swing.JLabel();
        jTextFieldFName = new javax.swing.JTextField();
        jLabelPricePerWeek = new javax.swing.JLabel();
        jTextFieldAccID = new javax.swing.JTextField();
        jTextFieldAddLine2 = new javax.swing.JTextField();
        jTextFieldAddLine1 = new javax.swing.JTextField();
        jLabelISBN = new javax.swing.JLabel();
        jButtonSearchCust = new javax.swing.JButton();
        jLabelEdition = new javax.swing.JLabel();
        jLabelAuthor = new javax.swing.JLabel();
        jLabelPricePerWeek2 = new javax.swing.JLabel();
        jTextFieldIBAN = new javax.swing.JTextField();
        jTextFieldDOB = new javax.swing.JTextField();
        jTextFieldBIC = new javax.swing.JTextField();
        jTextFieldLName = new javax.swing.JTextField();
        jButtonClearCust = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldPricePerWeek = new javax.swing.JTextField();
        jLabelPages1 = new javax.swing.JLabel();
        jLabelBookName1 = new javax.swing.JLabel();
        jLabelPublisher1 = new javax.swing.JLabel();
        jTextFieldBookName = new javax.swing.JTextField();
        jLabelPricePerWeek1 = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jTextFieldPages = new javax.swing.JTextField();
        jTextFieldPublisher = new javax.swing.JTextField();
        jLabelISBN1 = new javax.swing.JLabel();
        jButtonSearchBook = new javax.swing.JButton();
        jLabelEdition1 = new javax.swing.JLabel();
        jTextFieldAuthor = new javax.swing.JTextField();
        jLabelAuthor1 = new javax.swing.JLabel();
        jButtonClearBook = new javax.swing.JButton();
        jTextFieldEdition = new javax.swing.JTextField();
        jButtonListAllBooks = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelRental = new javax.swing.JLabel();
        jButtonConfirm = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jDateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rent Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 24), new java.awt.Color(102, 0, 0))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18), new java.awt.Color(102, 0, 0))); // NOI18N

        jLabelPages.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelPages.setText("Address Line 2:");

        jLabelBookName.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelBookName.setText("First Name:");

        jLabelPublisher.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelPublisher.setText("Address Line 1:");

        jTextFieldFName.setEditable(false);
        jTextFieldFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFNameActionPerformed(evt);
            }
        });

        jLabelPricePerWeek.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelPricePerWeek.setText("IBAN:");

        jTextFieldAccID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccIDActionPerformed(evt);
            }
        });

        jTextFieldAddLine2.setEditable(false);
        jTextFieldAddLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddLine2ActionPerformed(evt);
            }
        });

        jTextFieldAddLine1.setEditable(false);
        jTextFieldAddLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddLine1ActionPerformed(evt);
            }
        });

        jLabelISBN.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelISBN.setText("Account ID:");

        jButtonSearchCust.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonSearchCust.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaronm\\Documents\\AaronYear3Project\\LibraryRentalSystem\\images\\search.png")); // NOI18N
        jButtonSearchCust.setText("Search");
        jButtonSearchCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCustActionPerformed(evt);
            }
        });

        jLabelEdition.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelEdition.setText("Last Name:");

        jLabelAuthor.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelAuthor.setText("Date Of Birth:");

        jLabelPricePerWeek2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelPricePerWeek2.setText("BIC:");

        jTextFieldIBAN.setEditable(false);
        jTextFieldIBAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIBANActionPerformed(evt);
            }
        });

        jTextFieldDOB.setEditable(false);
        jTextFieldDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDOBActionPerformed(evt);
            }
        });

        jTextFieldBIC.setEditable(false);
        jTextFieldBIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBICActionPerformed(evt);
            }
        });

        jTextFieldLName.setEditable(false);
        jTextFieldLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLNameActionPerformed(evt);
            }
        });

        jButtonClearCust.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonClearCust.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaronm\\Documents\\AaronYear3Project\\LibraryRentalSystem\\images\\delete.png")); // NOI18N
        jButtonClearCust.setText("Clear");
        jButtonClearCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearCustActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaronm\\Documents\\AaronYear3Project\\LibraryRentalSystem\\images\\user.png")); // NOI18N
        jButton1.setText("List of Customers");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelPricePerWeek)
                        .addComponent(jLabelPricePerWeek2)
                        .addComponent(jLabelAuthor)
                        .addComponent(jLabelEdition)
                        .addComponent(jLabelBookName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addComponent(jLabelPages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonClearCust, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jTextFieldBIC)
                    .addComponent(jTextFieldIBAN)
                    .addComponent(jTextFieldDOB)
                    .addComponent(jTextFieldFName)
                    .addComponent(jTextFieldAddLine2)
                    .addComponent(jTextFieldAddLine1)
                    .addComponent(jTextFieldLName)
                    .addComponent(jTextFieldAccID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSearchCust, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAccID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelISBN))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookName))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEdition))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPublisher))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPages))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPricePerWeek))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPricePerWeek2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButtonSearchCust)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClearCust)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Book Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18), new java.awt.Color(102, 0, 0))); // NOI18N

        jTextFieldPricePerWeek.setEditable(false);
        jTextFieldPricePerWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPricePerWeekActionPerformed(evt);
            }
        });

        jLabelPages1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelPages1.setText("Pages:");

        jLabelBookName1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelBookName1.setText("Name:");

        jLabelPublisher1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelPublisher1.setText("Publisher:");

        jTextFieldBookName.setEditable(false);
        jTextFieldBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBookNameActionPerformed(evt);
            }
        });

        jLabelPricePerWeek1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelPricePerWeek1.setText("Price Per Week:");

        jTextFieldISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldISBNActionPerformed(evt);
            }
        });

        jTextFieldPages.setEditable(false);
        jTextFieldPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPagesActionPerformed(evt);
            }
        });

        jTextFieldPublisher.setEditable(false);
        jTextFieldPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPublisherActionPerformed(evt);
            }
        });

        jLabelISBN1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelISBN1.setText("Book ISBN:");

        jButtonSearchBook.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonSearchBook.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaronm\\Documents\\AaronYear3Project\\LibraryRentalSystem\\images\\search.png")); // NOI18N
        jButtonSearchBook.setText("Search");
        jButtonSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchBookActionPerformed(evt);
            }
        });

        jLabelEdition1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelEdition1.setText("Edition:");

        jTextFieldAuthor.setEditable(false);
        jTextFieldAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAuthorActionPerformed(evt);
            }
        });

        jLabelAuthor1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelAuthor1.setText("Author:");

        jButtonClearBook.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonClearBook.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaronm\\Documents\\AaronYear3Project\\LibraryRentalSystem\\images\\delete.png")); // NOI18N
        jButtonClearBook.setText("Clear");
        jButtonClearBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearBookActionPerformed(evt);
            }
        });

        jTextFieldEdition.setEditable(false);
        jTextFieldEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditionActionPerformed(evt);
            }
        });

        jButtonListAllBooks.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaronm\\Documents\\AaronYear3Project\\LibraryRentalSystem\\images\\smallBook.png")); // NOI18N
        jButtonListAllBooks.setText("List of Books");
        jButtonListAllBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListAllBooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPublisher1)
                            .addComponent(jLabelPages1)
                            .addComponent(jLabelEdition1)
                            .addComponent(jLabelBookName1)
                            .addComponent(jLabelISBN1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jTextFieldPublisher, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldBookName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldISBN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldEdition)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonListAllBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelPricePerWeek1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPricePerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelAuthor1)
                                .addGap(97, 97, 97)
                                .addComponent(jTextFieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonSearchBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(jButtonClearBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelISBN1)
                    .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBookName1)
                    .addComponent(jTextFieldBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdition1)
                    .addComponent(jTextFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPublisher1)
                    .addComponent(jTextFieldPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPages1)
                    .addComponent(jTextFieldPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAuthor1)
                    .addComponent(jTextFieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPricePerWeek1)
                    .addComponent(jTextFieldPricePerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSearchBook)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClearBook)
                    .addComponent(jButtonListAllBooks))
                .addContainerGap())
        );

        jLabelRental.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelRental.setText("Rental Date:");

        jButtonConfirm.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonConfirm.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaronm\\Documents\\AaronYear3Project\\LibraryRentalSystem\\images\\tick.png")); // NOI18N
        jButtonConfirm.setText("Confirm");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaronm\\Documents\\AaronYear3Project\\LibraryRentalSystem\\images\\exit.png")); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConfirm)
                .addGap(18, 18, 18)
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabelRental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRental))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirm)
                    .addComponent(jButtonBack))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(739, 788));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFNameActionPerformed

    private void jTextFieldAccIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccIDActionPerformed

    private void jTextFieldAddLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddLine2ActionPerformed

    private void jTextFieldAddLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddLine1ActionPerformed

    private void jButtonSearchCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCustActionPerformed

        searchCust();

    }//GEN-LAST:event_jButtonSearchCustActionPerformed

    public void searchCust() {
        String query = "select * from Account Where AccountNum = ?";
        try {
            pStatement = connection.prepareStatement(query);
            pStatement.setString(1, jTextFieldAccID.getText());
            result = pStatement.executeQuery();
            if (result.next()) {
                String s = result.getString("FirstName");
                jTextFieldFName.setText(s);
                s = result.getString("LastName");
                jTextFieldLName.setText(s);
                s = result.getString("AddLine1");
                jTextFieldAddLine1.setText(s);
                s = result.getString("AddLine2");
                jTextFieldAddLine2.setText(s);
                s = result.getString("DOB");
                jTextFieldDOB.setText(s);
                s = result.getString("IBAN");
                jTextFieldIBAN.setText(s);
                s = result.getString("BIC");
                jTextFieldBIC.setText(s);
                result.close();
                pStatement.close();
            } else {
                JOptionPane.showMessageDialog(null, "Account Number not found");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            try {
                result.close();
                pStatement.close();
            } catch (Exception ex) {

            }
        }
    }

    private void jTextFieldPricePerWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPricePerWeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPricePerWeekActionPerformed

    private void jTextFieldBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBookNameActionPerformed

    private void jTextFieldISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldISBNActionPerformed

    private void jTextFieldPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPagesActionPerformed

    private void jTextFieldPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPublisherActionPerformed

    private void jButtonSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchBookActionPerformed
        search();
    }//GEN-LAST:event_jButtonSearchBookActionPerformed

    public void search() {
        String query = "select * from Book Where ISBN = ?";
        try {
            pStatement = connection.prepareStatement(query);
            pStatement.setString(1, jTextFieldISBN.getText());
            result = pStatement.executeQuery();
            if (result.next()) {
                String s = result.getString("Name");
                jTextFieldBookName.setText(s);
                String s1 = result.getString("Edition");
                jTextFieldEdition.setText(s1);
                String s2 = result.getString("Publisher");
                jTextFieldPublisher.setText(s2);
                String s3 = result.getString("Pages");
                jTextFieldPages.setText(s3);
                String s4 = result.getString("Author");
                jTextFieldAuthor.setText(s4);
                String s5 = result.getString("PricePerWeek");
                jTextFieldPricePerWeek.setText(s5);
                result.close();
                pStatement.close();
            } else {
                JOptionPane.showMessageDialog(null, "ISBN not found");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            try {
                result.close();
                pStatement.close();
            } catch (Exception ex) {

            }
        }
    }

    private void jTextFieldAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAuthorActionPerformed

    private void jTextFieldIBANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIBANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIBANActionPerformed

    private void jTextFieldDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDOBActionPerformed

    private void jTextFieldBICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBICActionPerformed

    private void jTextFieldLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLNameActionPerformed

    private void jButtonClearBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearBookActionPerformed
        this.clearFormBook();
    }//GEN-LAST:event_jButtonClearBookActionPerformed

    private void jButtonClearCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearCustActionPerformed
        this.clearFormCust();
    }//GEN-LAST:event_jButtonClearCustActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        setVisible(false);
        BookManagement bM = new BookManagement();
        bM.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditionActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        String insert = "INSERT into RentBook (RentID,ISBN,AccountNum,Username,RentDate) values (?,?,?,?,?)";
        int id = generateRentID();
        try {

            pStatement = connection.prepareStatement(insert);

            pStatement.setInt(1, id);
            pStatement.setString(2, jTextFieldISBN.getText());
            pStatement.setString(3, jTextFieldAccID.getText());
            pStatement.setString(4, Login.username);
            pStatement.setString(5, ((JTextField) jDateChooser.getDateEditor().getUiComponent()).getText());
            pStatement.execute();
            JOptionPane.showMessageDialog(null, "Rental Confirmed");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex + ", please try again");

        }

        insert = "INSERT into RentBookAll (RentID,ISBN,AccountNum,Username,RentDate) values (?,?,?,?,?)";
        try {

            pStatement = connection.prepareStatement(insert);

            pStatement.setInt(1, id);
            pStatement.setString(2, jTextFieldISBN.getText());
            pStatement.setString(3, jTextFieldAccID.getText());
            pStatement.setString(4, Login.username);
            pStatement.setString(5, ((JTextField) jDateChooser.getDateEditor().getUiComponent()).getText());
            pStatement.execute();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex + ", please try again");

        }

        this.clearFormBook();
        this.clearFormCust();
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButtonListAllBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListAllBooksActionPerformed
        setVisible(false);
        BooksSearch bs = new BooksSearch(this);
        bs.setVisible(true);

    }//GEN-LAST:event_jButtonListAllBooksActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        CustomersSearch cs = new CustomersSearch(this);
        cs.setVisible(true);
        cs.ISBN = this.ISBN;

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonClearBook;
    private javax.swing.JButton jButtonClearCust;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonListAllBooks;
    private javax.swing.JButton jButtonSearchBook;
    private javax.swing.JButton jButtonSearchCust;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelAuthor1;
    private javax.swing.JLabel jLabelBookName;
    private javax.swing.JLabel jLabelBookName1;
    private javax.swing.JLabel jLabelEdition;
    private javax.swing.JLabel jLabelEdition1;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelISBN1;
    private javax.swing.JLabel jLabelPages;
    private javax.swing.JLabel jLabelPages1;
    private javax.swing.JLabel jLabelPricePerWeek;
    private javax.swing.JLabel jLabelPricePerWeek1;
    private javax.swing.JLabel jLabelPricePerWeek2;
    private javax.swing.JLabel jLabelPublisher;
    private javax.swing.JLabel jLabelPublisher1;
    private javax.swing.JLabel jLabelRental;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldAccID;
    private javax.swing.JTextField jTextFieldAddLine1;
    private javax.swing.JTextField jTextFieldAddLine2;
    private javax.swing.JTextField jTextFieldAuthor;
    private javax.swing.JTextField jTextFieldBIC;
    private javax.swing.JTextField jTextFieldBookName;
    private javax.swing.JTextField jTextFieldDOB;
    private javax.swing.JTextField jTextFieldEdition;
    private javax.swing.JTextField jTextFieldFName;
    private javax.swing.JTextField jTextFieldIBAN;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldLName;
    private javax.swing.JTextField jTextFieldPages;
    private javax.swing.JTextField jTextFieldPricePerWeek;
    private javax.swing.JTextField jTextFieldPublisher;
    // End of variables declaration//GEN-END:variables

    private void clearFormBook() {

        this.jTextFieldISBN.setText("");
        this.jTextFieldBookName.setText("");
        this.jTextFieldEdition.setText("");
        this.jTextFieldPublisher.setText("");
        this.jTextFieldPages.setText("");
        this.jTextFieldAuthor.setText("");
        this.jTextFieldPricePerWeek.setText("");
    }

    private void clearFormCust() {
        this.jTextFieldAccID.setText("");
        this.jTextFieldFName.setText("");
        this.jTextFieldLName.setText("");
        this.jTextFieldAddLine1.setText("");
        this.jTextFieldAddLine2.setText("");
        this.jTextFieldDOB.setText("");
        this.jTextFieldIBAN.setText("");
        this.jTextFieldBIC.setText("");
    }
}
